# issues are repository scoped, need to run from default/main branch
# cant trigger issues workflow from feature branches

name: Handle Issues
on:
  issues
jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "${{ toJson(github.event) }}"