name: Practice_Project
on:
  push:
    branches:
      - second-action-exercise

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        working-directory:  "04 Practice Project (Start)"
        run: npm ci

      - name: Lint
        working-directory:  "04 Practice Project (Start)"
        run: npm run lint

      - name: Test
        working-directory:  "04 Practice Project (Start)"
        run: npm run test

      - name: Build
        working-directory:  "04 Practice Project (Start)"
        run: npm run build

      - name: Deploy
        run: echo "Deploying ..."
