name: Events Demo 1
on: workflow_dispatch  # [push] removed push, not to trigger when working on other workflows on main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: Events_Demo_Project
        run: npm ci
      - name: Test code
        working-directory: Events_Demo_Project
        run: npm run test
      - name: Build code
        working-directory: Events_Demo_Project
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."