name: Output information
on: 
  push:
    branches:
      - second-action-react-demo
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github context
        run: echo "${{ toJson(github) }}"